### ISSUE TITLE
Hashable instance for Float/Double inconsistent for negative and positive zero

### ISSUE THREAD

**Issue by glguy** [tibbe/hashable#116] opened 2016-08-15 20:25 UTC
Things that are `(==)` should have the same `hash` as documented in the `Hashable` class, but:

```
Prelude Data.Hashable> hash (0 :: Float) 
0
Prelude Data.Hashable> hash (-0 :: Float) 
2147483648
Prelude Data.Hashable> hash (0 :: Double) 
0
Prelude Data.Hashable> hash (-0 :: Double) 
-9223372036854775808
Prelude Data.Hashable> 0 == (-0 :: Double)
True
Prelude Data.Hashable> 0 == (-0 :: Float)
True
```

**Comment by hvr** [comment] 2019-05-05 21:54
Duplicate of #173

**Closed by hvr** 2019-05-05 21:54 UTC
